name: DADEC
channels:
  - conda-forge
  - bioconda
  - defaults
  - pkgs/main
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _sysroot_linux-64_curr_repodata_hack=3=h69a702a_16
  - abseil-cpp=20220623.0=h8cdb687_6
  - bamtools=2.5.2=hdcf5f25_5
  - binutils_impl_linux-64=2.40=ha1999f0_7
  - binutils_linux-64=2.40=hb3c18ed_0
  - boost=1.85.0=he8689d4_4
  - bzip2=1.0.8=h4bc722e_7
  - c-ares=1.33.1=heb4867d_0
  - ca-certificates=2025.8.3=hbd8a1cb_0
  - gatb=1.4.2=h56e2c18_4
  - gcc_impl_linux-64=14.1.0=h3c94d91_0
  - gcc_linux-64=14.1.0=h3f71edc_0
  - gxx_impl_linux-64=14.1.0=h8d00ecb_0
  - gxx_linux-64=14.1.0=hc55ae77_0
  - hdf5=1.14.3=nompi_hdf9ad27_105
  - icu=75.1=he02047a_0
  - jemalloc=5.3.0=hcb278e6_0
  - k8=1.2=he8db53b_6
  - kernel-headers_linux-64=3.10.0=h4a8ded7_16
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.21.3=h659f571_0
  - ld_impl_linux-64=2.40=hf3520f5_7
  - libabseil=20220623.0=cxx17_h05df665_6
  - libaec=1.1.3=h59595ed_0
  - libblas=3.9.0=31_h59b9bed_openblas
  - libboost=1.85.0=h0ccab89_4
  - libboost-devel=1.85.0=h00ab1b0_4
  - libboost-headers=1.85.0=ha770c72_4
  - libboost-python=1.85.0=py39h1eb36c5_4
  - libboost-python-devel=1.85.0=py39he8689d4_4
  - libcblas=3.9.0=31_he106b2a_openblas
  - libcurl=8.9.1=hdb1bdb2_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=hd590300_2
  - libexpat=2.6.2=h59595ed_0
  - libffi=3.4.2=h7f98852_5
  - libgcc=14.1.0=h77fa898_1
  - libgcc-devel_linux-64=14.1.0=h5d3d1c9_100
  - libgcc-ng=14.1.0=h69a702a_1
  - libgfortran-ng=14.1.0=h69a702a_0
  - libgfortran5=14.1.0=hc5f4f2c_0
  - libgomp=14.1.0=h77fa898_1
  - libjemalloc=5.3.0=hcb278e6_0
  - liblapack=3.9.0=31_h7ac8fdf_openblas
  - libnghttp2=1.58.0=h47da74e_1
  - libnsl=2.0.1=hd590300_0
  - libopenblas=0.3.29=ha39b09d_0
  - libprotobuf=3.21.12=hfc55251_2
  - libprotobuf-static=3.21.12=hfc55251_2
  - libsanitizer=14.1.0=hcba0ae0_0
  - libsqlite=3.46.0=hde9e2c9_0
  - libssh2=1.11.0=h0841786_0
  - libstdcxx=14.1.0=hc0a3c3a_1
  - libstdcxx-devel_linux-64=14.1.0=h5d3d1c9_100
  - libstdcxx-ng=14.1.0=h4852527_1
  - libuuid=2.38.1=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=h4ab18f5_1
  - minimap2=2.28=h577a1d6_4
  - ncurses=6.5=he02047a_1
  - numpy=2.0.2=py39h9cb892a_0
  - openssl=3.5.2=h26f9b46_0
  - pip=24.2=pyhd8ed1ab_0
  - pkg-config=0.29.2=h4bc722e_1009
  - protobuf=4.21.12=py39h227be39_0
  - python=3.9.19=h0755675_0_cpython
  - python_abi=3.9=8_cp39
  - readline=8.2=h8228510_1
  - sdsl-lite=2.1.1=h00ab1b0_1002
  - setuptools=72.2.0=pyhd8ed1ab_0
  - six=1.17.0=pyhe01879c_1
  - sparsehash=2.0.4=hcb278e6_1
  - sqlite=3.46.0=h6d4b2fc_0
  - sysroot_linux-64=2.17=h4a8ded7_16
  - tk=8.6.13=noxft_h4845f30_101
  - tzdata=2024a=h8827d51_1
  - wheel=0.44.0=pyhd8ed1ab_0
  - xz=5.2.6=h166bdaf_0
  - zlib=1.3.1=h4ab18f5_1
  - zstd=1.5.6=ha6fb4c9_0
